# Site settings
title: Разработка сайтов компаний.
email: z@illus0r.net
baseurl: '' # the subpath of your site, e.g. /blog/
#url: http://dianov.org # the base hostname & protocol for your site
url: http://localhost:3000 # the base hostname & protocol for your site
twitter_username: z_o_r
github_username:  illus0r
# not sure works for github
#destination: _site

# Build settings
markdown: kramdown

prose:
  # rooturl: "_posts"
  media: "media"
  siteurl: "http://dianov.org"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
